import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { SpecifyAgentAdapter } from './copilotSpecify';

type BoundarySpecifyAdapterConfig = {
  ok?: boolean;
  featureDirectory?: string;
  specMarkdown?: string;
};

const DEFAULT_FEATURE_DIRECTORY = 'specs/0001-hello-world-feature';
const DEFAULT_SPEC_MARKDOWN = `# Hello-world feature

Prompt: Build a hello-world feature

This specification was generated by the deterministic Specify boundary adapter.
`;

const isSafeRepoRelativePath = (value: string): boolean => {
  if (value.trim().length === 0 || path.isAbsolute(value)) {
    return false;
  }

  return !value.split(/[\\/]+/).includes('..');
};

const readBoundaryConfig = async (adapterPath: string): Promise<BoundarySpecifyAdapterConfig> =>
  JSON.parse(await readFile(adapterPath, 'utf8')) as BoundarySpecifyAdapterConfig;

export const createBoundarySpecifyAgentAdapter = (
  adapterPath = process.env.CONCIERGE_TEST_COPILOT_ADAPTER
): SpecifyAgentAdapter | undefined => {
  if (adapterPath === undefined || adapterPath.length === 0) {
    return undefined;
  }

  return async (request) => {
    const config = await readBoundaryConfig(adapterPath);
    if (config.ok === false) {
      throw new Error('Specify boundary adapter was configured to fail.');
    }

    const featureDirectory = config.featureDirectory ?? DEFAULT_FEATURE_DIRECTORY;
    if (!isSafeRepoRelativePath(featureDirectory)) {
      throw new Error('Specify boundary adapter featureDirectory must be repo-relative.');
    }

    const featureDir = path.join(request.repositoryPath, featureDirectory);
    await mkdir(path.join(request.repositoryPath, '.specify'), { recursive: true });
    await mkdir(featureDir, { recursive: true });
    await writeFile(
      path.join(request.repositoryPath, '.specify', 'feature.json'),
      `${JSON.stringify({ feature_directory: featureDirectory }, null, 2)}\n`,
      'utf8'
    );
    await writeFile(path.join(featureDir, 'spec.md'), config.specMarkdown ?? DEFAULT_SPEC_MARKDOWN, 'utf8');

    request.onUpdate?.('Creating feature directory...');
    request.onUpdate?.(`Writing spec.md to ${featureDirectory}/spec.md`);
    request.onUpdate?.('Specify complete');
  };
};
